# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- rm -rf ~/Library/Developer/Xcode/DerivedData
- rm -rf Example/Pods
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ios-app.xcworkspace -scheme ios-app-Example -destination 'platform=iOS Simulator,name=iPhone 8' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
